apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "tutorial"
  annotations:
    backstage.io/techdocs-ref: dir:../docs/tutorial
    github.com/project-slug: naruse666/backstage-tutorial
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
  dependsOn: 
  - resource:default/tutorial-db
  providesApis:
  - tutorial-graphql-api
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: tutorial
  description: This is sample system
spec:
  owner: user:guest
