name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request: [opened, syncronized]
jobs:
  GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
        if: false
